name: CD

on: [
  workflow_call,
  workflow_dispatch
]

jobs:
  Prepare-Image:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: 'Building App JARs'
        run: make build-app
      - name: 'Building App Image'
        run: make build-docker-image
      - name: 'Extracting App image to upload in the next step'
        run: make save-docker-image
      - name: 'Uploading built docker image'
        uses: actions/upload-artifact@v4
        with:
          name: image-artifacts
          path: ./build/images

  Deploy-Image:
    needs: Prepare-Image
    runs-on: ubuntu-22.04
    steps:
      - name: 'Deploying App image'
        run: echo "Deploying App image... (mocked)"
